# Generated by Django 3.1.5 on 2021-06-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeApi', '0002_meme_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
