# Generated by Django 3.1.5 on 2021-06-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeApi', '0003_auto_20210620_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='media')),
            ],
        ),
    ]
